language: node_js

sudo: true

node_js:
  - "10.16"

install:
  - ./scripts/checkSimulationContracts.bash
  - yarn install
  - yarn global add ganache-cli truffle
  - pushd enigma-js && yarn install && popd

before_script:
  - ganache-cli -p 9545 -i 4447 -d &
  - sleep 5

script:
  - set -e
  - rm -rf build
  - truffle compile
  - truffle migrate --reset --network develop
  - pushd enigma-js && yarn build && popd
  - SGX_MODE=SW truffle migrate --reset --network develop
  - pushd enigma-js && SGX_MODE=SW yarn test && popd

after_success:
  - pushd enigma-js && yarn report-coverage && popd
